name: CI-CD pipeline

on:
push:
branches:
- main

jobs:

build:
runs-on: self-hosted


steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Setup JDK
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: "17"
      cache: maven

  - name: Build with Maven
    run: mvn clean package -DskipTests

  - name: Upload Artifact
    uses: actions/upload-artifact@v4
    with:
      name: app-jar
      path: target/*.jar

security-scan:
runs-on: ubuntu-latest
needs: build

```
steps:
  - uses: actions/checkout@v4

  - name: Install Trivy
    run: |
      sudo apt-get update
      sudo apt-get install wget gnupg -y
      wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
      echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
      sudo apt-get update
      sudo apt-get install trivy -y

  - name: Trivy Scan
    run: trivy fs .
```

test:
runs-on: self-hosted
needs: security-scan

```
steps:
  - uses: actions/checkout@v4

  - name: Setup JDK
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: "17"

  - name: Run Tests
    run: mvn test
```

sonar:
runs-on: ubuntu-latest
needs: test

```
steps:
  - uses: actions/checkout@v4

  - name: Setup JDK
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: "17"

  - name: Build Project
    run: mvn clean verify

  - name: SonarCloud Scan
    uses: SonarSource/sonarqube-scan-action@v6
    with:
      args: >
        -Dsonar.projectKey=anjalinaragude_java-project-github-action
        -Dsonar.organization=anjalinaragude
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

docker-build:
runs-on: ubuntu-latest
needs: sonar

```
steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Download Artifact
    uses: actions/download-artifact@v4
    with:
      name: app-jar
      path: app

  - name: Login to DockerHub
    uses: docker/login-action@v3
    with:
      username: ${{ vars.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: Setup Buildx
    uses: docker/setup-buildx-action@v3

  - name: Build and Push Image
    uses: docker/build-push-action@v6
    with:
      context: .
      file: ./Dockerfile
      push: true
      tags: anjalinaragude/bankapp:latest
```

deploy:
runs-on: ubuntu-latest
needs: docker-build

```
steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v2
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}

  - name: Install kubectl
    run: |
      curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin/

  - name: Update kubeconfig
    run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name action-eks-cluster

  - name: Check Cluster
    run: kubectl get nodes

  - name: Deploy to Kubernetes
    run: kubectl apply -f src/ds.yml
```
